[build]
  base = ""
  publish = "build"
  command = "npm run build:prod"

[build.environment]
  NODE_VERSION = "18"
  NODE_ENV = "production"

[context.production.environment]
  NODE_ENV = "production"

[context.production.deploy-redirects]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
